# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/dpramNxMx36/dpramNxMx36.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpramNxMx36 || ORIG_REF_NAME==dpramNxMx36} -quiet] -quiet

# IP: ip/dpramNxMx32/dpramNxMx32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dpramNxMx32 || ORIG_REF_NAME==dpramNxMx32} -quiet] -quiet

# XDC: ip/dpramNxMx36/dpramNxMx36_ooc.xdc

# XDC: ip/dpramNxMx32/dpramNxMx32_ooc.xdc
